### ISSUE TITLE
Thermal Golems won't show up in the Golem Guide Book

### ISSUE THREAD

**Issue by BugmanBugman** [skyjay1/Thermal-Golems-Addon#1]
https://pastebin.com/RBzVVwgW

**Comment by BugmanBugman** [comment]
![2020-04-26_16 01 37](https://user-images.githubusercontent.com/40730042/80319679-590d8c80-87d7-11ea-8486-a4dd61580255.png)
Scratch that, Thermal Golems aren't spawning period. Maybe the new Thermal update broke it?

**Comment by Sereath** [comment]
Here to report the same, very unfortunate.

**Comment by skyjay1** [comment]
Thermal Golems Addon is no longer maintained because it's meant for an old version of Minecraft (1.12). Thermal Foundation support has been integrated into Extra Golems for 1.16+, 1.12 is no longer supported
